version: '3.9'

services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: local
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: